/*
 * Schneider Charge PCM API
 *
 * This is the local API used for PCM by Wiser Hub to control Schneider Charge
 *
 * API version: 1.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ElectricalSettings struct {
	// max current in Ampere
	IMaxInstallation int32 `json:"iMaxInstallation"`
	// User set max current in Ampere. Can not be greater than iMaxInstallation value
	IMaxUser int32 `json:"iMaxUser"`
}
