/*
 * Schneider Charge PCM API
 *
 * This is the local API used for PCM by Wiser Hub to control Schneider Charge
 *
 * API version: 1.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Current struct {

	Current float64 `json:"current"`
}
