/*
 * Schneider Charge PCM API
 *
 * This is the local API used for PCM by Wiser Hub to control Schneider Charge
 *
 * API version: 1.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/",
		Index,
	},

	Route{
		"EvseV1PCMLoginLoginPost",
		strings.ToUpper("Post"),
		"/evse/v1/PCM/login/login",
		EvseV1PCMLoginLoginPost,
	},

	Route{
		"EvseV1PCMElectricalSettingsGet",
		strings.ToUpper("Get"),
		"/evse/v1/PCM/electricalSettings",
		EvseV1PCMElectricalSettingsGet,
	},

	Route{
		"EvseV1PCMSetpointGet",
		strings.ToUpper("Get"),
		"/evse/v1/PCM/setpoint",
		EvseV1PCMSetpointGet,
	},

	Route{
		"EvseV1PCMSetpointPost",
		strings.ToUpper("Post"),
		"/evse/v1/PCM/setpoint",
		EvseV1PCMSetpointPost,
	},

	Route{
		"EvseV1PCMStatusGet",
		strings.ToUpper("Get"),
		"/evse/v1/PCM/status",
		EvseV1PCMStatusGet,
	},
}
